version: "3.8"
services:

  frontend:
    image: 127.0.0.1:5000/angular-ui:approach3
    build:
      context: ./angular-ui
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    environment:
      - TZ=Europe/Berlin
    deploy:
      replicas: 1
      placement:
        constraints:
          - "node.role==manager"

  geth:
    image: 127.0.0.1:5000/geth-node:approach3
    build:
      context: ./geth
      dockerfile: Dockerfile
    ports:
      - "8545:8545"
      - "8546:8546"
    environment:
      - TZ=Europe/Berlin
    deploy:
      replicas: 1
      placement:
        constraints:
          - "node.role==manager"

  nonce-manager:
    image: 127.0.0.1:5000/nonce-manager:approach3
    build:
      context: ./redis
      dockerfile: Dockerfile
    ports:
      - "6379:6379"
    deploy:
      replicas: 1
      placement:
        constraints:
          - "node.role==manager"
    environment:
      - TZ=Europe/Berlin

  tx-creation:
    image: 127.0.0.1:5000/tx-creating-machine:approach3
    build:
      context: ./approach3
      dockerfile: Dockerfile
    ports:
      - target: 8080
        # published: 8080
        mode: host
    environment:
      - TZ=Europe/Berlin
      - PORT=8080
      - PRIVATE_KEY=bcc6d4aa1e277f085b3e11f2c1e6f14dd04e8108c823898e06fa5287c2bf1a92
      - NODE_URL=http://geth:8545
      - CONTRACT_ADDRESS=0x17cB057648a03dE335c773C7F6b7719c63A32eB7
      - MACHINE_ID={{.Task.Name}}
      - REDIS_HOST=nonce-manager
      - REDIS_PORT=6379
    deploy:
      replicas: 1
      placement:
        max_replicas_per_node: 1
        constraints:
          - "node.labels.txcreation==yes"